// This file is auto-generated by @hey-api/openapi-ts

export const EventMessageTypeModelSchema = {
    enum: ['Default', 'Info', 'Error', 'Success', 'Warning'],
    type: 'string'
} as const;

export const NotificationHeaderModelSchema = {
    required: ['category', 'message', 'type'],
    type: 'object',
    properties: {
        message: {
            type: 'string'
        },
        category: {
            type: 'string'
        },
        type: {
            '$ref': '#/components/schemas/EventMessageTypeModel'
        }
    },
    additionalProperties: false
} as const;

export const UnusedMediaViewModelSchema = {
    required: ['items'],
    type: 'object',
    properties: {
        items: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        }
    },
    additionalProperties: false
} as const;