// This file is auto-generated by @hey-api/openapi-ts

export type EventMessageTypeModel = 'Default' | 'Info' | 'Error' | 'Success' | 'Warning';

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type UnusedMediaViewModel = {
    name: string;
    key: string;
    icon: string;
};

export type UnusedMediaResponse = ((UnusedMediaViewModel));

export type UnusedMediaError = (unknown);

export type DeleteData = {
    body?: Array<(UnusedMediaViewModel)>;
};

export type DeleteResponse = (string);

export type DeleteError = (unknown);

export type RecycleBinMediaResponse = ((UnusedMediaViewModel));

export type RecycleBinMediaError = (unknown);

export type RestoreAllData = {
    body?: Array<(UnusedMediaViewModel)>;
};

export type RestoreAllResponse = ((UnusedMediaViewModel));

export type RestoreAllError = (unknown);